---
name: Run Behavioral Tests
on:
  - push
  - pull_request
jobs:
  yamllint:
    name: Run behave tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.x"
      - name: Run tests
        run: |
          python3 -m pip install 'behave>=1.2.7dev6' ruamel.yaml
          behave
